version: "3.7"
services:
  db:
    container_name: "user_crud_database"
    image: postgres:14-alpine
    command: postgres -c 'max_connections=1000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=LRCmNXvWPb4V2Faquc3SmhJU
      # NB! new databases are only added, if on startup volume for db is empty!
      # either recreate the volume or add new databases manually via sql with CREATE database "database-name"
      - >-
        POSTGRES_MULTIPLE_DATABASES=
        "user-crud",
        "user-crud-test"
    ports:
      - "6432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
     pgdata:
